blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('<int:yr>/<int:mn>/<int:dy>/<slug:slug>/',views.post_detail,name='post_detail'),
    path('<int:id>/share/',views.post_share,name='post_share')
    # path('<int:id>/<slug:slug>/',views.post_detail,name='post_detail')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse



class PublishedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    objects = models.Manager()
    published = PublishedManager()
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'


    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,choices=Status,default=Status.DRAFT)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='blog_post',null=True)

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        # return reverse("blog:post_detail", args=[self.id,self.slug])
        return reverse("blog:post_detail", args=[self.publish.year,self.publish.month,self.publish.day,self.slug])
    

blog/forms.py
from django import forms 

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
from django.core.paginator import Paginator
from django.views.generic import ListView
from .forms import EmailPostForm
from django.http import HttpResponse
from django.core.mail import send_mail


def post_share(request,id):
    post = get_object_or_404(Post,id=id,status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            message = (f"Read the title {post.title} at {post_url}\n\n"
                       f"{cd['name']}\'s Comment: {cd['comments']}")
            subject = (
                f"{cd['name']} ({cd['email']})"
                f"ecommends you read {post.title}"
            )
            
            send_mail(message=message,subject=subject,from_email=None,recipient_list=[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,'blog/post/share.html',{'form':form,'post':post,'sent':sent})         



class PostListView(ListView):
    template_name = 'blog/post/list.html'
    context_object_name = 'posts'
    queryset = Post.published.all()
    paginate_by = 2

# Create your views here.
# def post_list(request):
#     posts_lists = Post.published.all()

#     paginator = Paginator(posts_lists,2)
#     page_number = request.GET.get('page',1)
#     posts = paginator.get_page(page_number)
#     print(posts.has_previous())
    

    # return render(request,'blog/post/list.html',{'posts':posts})

def post_detail(request,yr,mn,dy,slug):
    post = get_object_or_404(Post,status=Post.Status.PUBLISHED,slug=slug,publish__year=yr,publish__month=mn,publish__day=dy)
  

    return render(request,'blog/post/detail.html',{'post':post})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}{% endblock %}
    </title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        
        {% block content %}
            
        {% endblock %}
            

    </div>
    <div id="sidebar">
       <h2>My blog</h2>
       <p>This is my blog</p>
    </div>
    <div>

    
</body>
</html>

blog/templates/blog/include/pagination.html
<div class="pagination">
<span class="step-links">
    
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number}}">Previous</a>
    {% endif %}
<span class="current">  
    Page {{ page.number }} of {{ page.paginator.num_pages }}  
</span>    


{% if page.has_next %}
    <a href="?page={{page.next_page_number}}">Next</a>
{% endif %}

</span>
</div>
    
        

blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}


{% block title %}
    comment Form
{% endblock  %}


{% block content %}
    <form action="" method="post">
       {% csrf_token %}
       {{ form }}

       <input type="submit" value="Submit">

    </form>
{% endblock %}
    
    

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}


{% block title %}
    {{ post.title }}
{% endblock  %}


{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish}} by {{post.author}}</p>
    {{ post.body|linebreaks}}
    <p>
   <a href='{% url "blog:post_share" post.id %}'>
    Share this post
 </a>
</p>
{% endblock  %}
    
    

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}


{% block title %}
    My Blog
{% endblock %}


{% block content %}


{% for post in posts  %}
<h2>
 <a href="{{ post.get_absolute_url}}">{{ post.title }}</a>
 </h2>
 <p class="date"> Published {{post.publish}} by {{post.author}}</p> 

  {{ post.body|truncatewords:10|linebreaks }}  
{% endfor %}
    
  <div>
  {% include 'blog/include/pagination.html' with page=page_o  %} 
 </div>  
{% endblock %}

   
    
    

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}


{% block title %}
    Share comment
{% endblock %}


{% block content %}

{% if sent %}
    <h1>E-mail successfully sent</h1>
 <p>
 "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
 </p>

 {% else %}

  <h1>Share "{{ post.title }}" by e-mail</h1>

<form method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Send e-mail">
</form>
{% endif %}
    
    
{% endblock  %}
    
    